const CHANGE_BANNER_LIST = 'CHANGE_BANNER_LIST' 
const CHANGE_PRO_LIST = 'CHANGE_PRO_LIST' 
const CHANGE_KIND_LIST =  'CHANGE_KIND_LIST'

export {
  CHANGE_BANNER_LIST,
  CHANGE_PRO_LIST,
  CHANGE_KIND_LIST
}